siteUid: null
sortOrder: 42
template: /_calendar/resources/event_data
uriParts:
  - the-link/calendar/resources/event_data/
  -
    - number
    - \d+
uriPattern: 'the-link/calendar/resources/event_data/<number:\d+>'
