siteUid: null
sortOrder: 33
template: /the-link/event
uriParts:
  - the-link/event/
  -
    - number
    - \d+
  - /
  -
    - year
    - '\d{4}'
  - /
  -
    - month
    - '(?:0?[1-9]|1[012])'
  - /
  -
    - day
    - '(?:0?[1-9]|[12][0-9]|3[01])'
uriPattern: 'the-link/event/<number:\d+>/<year:\d{4}>/<month:(?:0?[1-9]|1[012])>/<day:(?:0?[1-9]|[12][0-9]|3[01])>'
