siteUid: null
sortOrder: 24
template: /_pages/interior_the_link
uriParts:
  0: the-link/month/calendar/
  1:
    - slug
    - '[^\/]+'
  3: /
  4:
    - year
    - '\d{4}'
  6: /
  7:
    - month
    - '(?:0?[1-9]|1[012])'
uriPattern: 'the-link/month/calendar/<slug:[^\/]+>/<year:\d{4}>/<month:(?:0?[1-9]|1[012])>'
