siteUid: null
sortOrder: 22
template: /_pages/interior_the_link
uriParts:
  0: the-link/month/
  1:
    - year
    - '\d{4}'
  3: /
  4:
    - month
    - '(?:0?[1-9]|1[012])'
uriPattern: 'the-link/month/<year:\d{4}>/<month:(?:0?[1-9]|1[012])>'
