siteUid: null
sortOrder: 79
template: /calendar-demo/resources/event_data
uriParts:
  - calendar-demo/resources/event_data/
  -
    - number
    - \d+
uriPattern: 'calendar-demo/resources/event_data/<number:\d+>'
