siteUid: null
sortOrder: 21
template: /the-link/mini_cal
uriParts:
  - the-link/mini_cal/
  -
    - year
    - '\d{4}'
  - /
  -
    - month
    - '(?:0?[1-9]|1[012])'
uriPattern: 'the-link/mini_cal/<year:\d{4}>/<month:(?:0?[1-9]|1[012])>'
