siteUid: null
sortOrder: 71
template: /_calendar/week
uriParts:
  0: the-link/calendar/week/
  1:
    - year
    - '\d{4}'
  3: /
  4:
    - month
    - '(?:0?[1-9]|1[012])'
  6: /
  7:
    - day
    - '(?:0?[1-9]|[12][0-9]|3[01])'
uriPattern: 'the-link/calendar/week/<year:\d{4}>/<month:(?:0?[1-9]|1[012])>/<day:(?:0?[1-9]|[12][0-9]|3[01])>'
