field: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
fieldLayouts:
  24f47854-0798-4ae4-bb34-061e5a00a167:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6a083dd0-c3a0-40c7-a437-2c5c4610fa50 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32a6ac9a-fc3f-4004-9405-866996000467
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 56a3fb3c-0016-4cdb-acbe-817fbf2313a7
        userCondition: null
fields:
  6a083dd0-c3a0-40c7-a437-2c5c4610fa50: # Heading
    columnSuffix: pwlhozye
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: calendar
name: Calendar
sortOrder: 6
