field: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
fieldLayouts:
  67b3defe-82e7-4613-9aa0-0a6c02bc0b02:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0d01ac2a-6f7f-4925-8c97-10d917e18c84 # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 965e5b68-9fb4-420f-b6be-7bf75d5d16ff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6dc1ef68-7606-4254-8f3e-ab00a4a0b146 # Button Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0af1f30c-23c0-412d-8cd9-56043147e74e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0afdac73-846a-4985-a071-851fed756ca9 # Button Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 548b0e08-7744-4dd9-be93-431f94f05c9e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9106d75e-ab2e-4394-989c-e5865e75ee12
        userCondition: null
fields:
  0afdac73-846a-4985-a071-851fed756ca9: # Button Text
    columnSuffix: null
    contentColumnType: string(256)
    fieldGroup: null
    handle: buttonText
    instructions: 'Button Text'
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 64
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'Button Text'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  0d01ac2a-6f7f-4925-8c97-10d917e18c84: # Title
    columnSuffix: null
    contentColumnType: string(512)
    fieldGroup: null
    handle: panelTitle
    instructions: Title
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: 128
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: Title
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6dc1ef68-7606-4254-8f3e-ab00a4a0b146: # Button Link
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonHref
    instructions: 'Button Link'
    name: 'Button Link'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: callToAction
name: 'Call To Action Panel'
sortOrder: 5
