field: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
fieldLayouts:
  37d643c2-a5a2-4c27-a5d7-a7d8aacc9399:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cb6d8f3b-a601-41e8-8045-6ab67f0d37b8 # Waterloo Innovation Park Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f62674e-6f9f-461d-9d33-b855e5903814
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e7c7e219-044d-4f4e-813d-a85552002327 # Waterloo Innovation Park Contact Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb2e301b-a953-4a53-af36-8824af979a95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4f9aa02-65e9-4d0c-8726-9a5782e118c8 # Waterloo Innovation Park Inquiries Email Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bef20ddf-facf-4f7b-aaa8-beaceae028e3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d970ca81-be2c-4ab3-a6d4-156dafe345fe # Waterloo Innovation Park Inquiries Phone Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eca1e4b3-1ab8-43f0-840f-34fe77108c51
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e63c55f2-78e4-45cc-9bd8-445b5d5b071a # Waterloo Innovation Park Inquiries Phone Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 020c5900-48d6-47cd-96d3-d4c3aa083b7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a03da100-4469-4fa1-925f-20e983f46792 # Waterloo Innovation Park Inquiries Phone Link 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4594fe58-7ac3-498a-9fc1-c99f9ddaff47
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4a72afd-9824-4711-8c7c-654a73ab4125 # Waterloo Innovation Park Inquiries Phone Display 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d4aed8a-f10a-40a9-b2dd-d19e2d095e6d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fbccfcff-4fb4-431b-99a0-3bf93c927097 # Waterloo Innovation Park Leasing Phone Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8be3d335-bf17-4640-8059-efae765ff759
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: faa07140-e5cb-4752-9790-0260ba2b62da # Waterloo Innovation Park Leasing Phone Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8f69bb4-2152-4e17-a045-6a09dc85ba26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3b86eba-c5cd-4b35-99db-9cfe005af4a3 # Waterloo Innovation Park Emergency Phone Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b9ccbd5-5d4c-4c99-8b7f-8cdbc6b30d78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9953bc18-4725-4380-adb8-e62a02c6f0d2 # Waterloo Innovation Park Emergency Phone Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4a75298-6d91-4e82-b832-59cf8dbc2388
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b87bb998-aa92-42fc-aee9-1adb2c624a30 # The Link Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7680b32e-84b4-4423-9c99-4b6443f82880
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ab1fc90-55da-4dd5-87ff-80cf0364b381 # The Link Contact Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3ab989a-190b-4e2a-b414-b30c9848514d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1019bad3-fa23-4cdb-bb2b-711a0f1e7bdd # The Link Hours of Operation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08aed9a8-1529-403d-82d6-59a3f9eae224
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a551636e-985a-439e-b78e-c173d8fcc171 # The Link Phone Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6804dc5c-127a-4e4a-9ddb-ffa9f9857aef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac896e2d-c524-475b-9740-71f975b24844 # The Link Phone Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18e5459c-01ea-4d19-b0c1-d442f5f2920e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4461882-7624-4f6f-ac6c-c06ea4a4689d # The Link Email Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dddf2461-472e-465b-a36d-5866c010d7ff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e052d9ee-ca0a-4e1b-b451-41a37658bdc8
        userCondition: null
fields:
  8ab1fc90-55da-4dd5-87ff-80cf0364b381: # The Link Contact Message
    columnSuffix: yurgfxyo
    contentColumnType: text
    fieldGroup: null
    handle: theLinkContactMessage
    instructions: null
    name: 'The Link Contact Message'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1019bad3-fa23-4cdb-bb2b-711a0f1e7bdd: # The Link Hours of Operation
    columnSuffix: oxghlrrq
    contentColumnType: text
    fieldGroup: null
    handle: theLinkHoursOfOperation
    instructions: null
    name: 'The Link Hours of Operation'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9953bc18-4725-4380-adb8-e62a02c6f0d2: # Waterloo Innovation Park Emergency Phone Display
    columnSuffix: rfhuaume
    contentColumnType: text
    fieldGroup: null
    handle: wipEmergencyPhoneDisplay
    instructions: null
    name: 'Waterloo Innovation Park Emergency Phone Display'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a03da100-4469-4fa1-925f-20e983f46792: # Waterloo Innovation Park Inquiries Phone Link 2
    columnSuffix: eyhqxlll
    contentColumnType: text
    fieldGroup: null
    handle: wipInquiriesPhoneLink2
    instructions: null
    name: 'Waterloo Innovation Park Inquiries Phone Link 2'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a4f9aa02-65e9-4d0c-8726-9a5782e118c8: # Waterloo Innovation Park Inquiries Email Link
    columnSuffix: sgsdfnqy
    contentColumnType: text
    fieldGroup: null
    handle: wipInquiriesEmailLink
    instructions: null
    name: 'Waterloo Innovation Park Inquiries Email Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a551636e-985a-439e-b78e-c173d8fcc171: # The Link Phone Link
    columnSuffix: ikgybbsa
    contentColumnType: text
    fieldGroup: null
    handle: theLinkPhoneLink
    instructions: null
    name: 'The Link Phone Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ac896e2d-c524-475b-9740-71f975b24844: # The Link Phone Display
    columnSuffix: sfmjcvyg
    contentColumnType: text
    fieldGroup: null
    handle: theLinkPhoneDisplay
    instructions: null
    name: 'The Link Phone Display'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b3b86eba-c5cd-4b35-99db-9cfe005af4a3: # Waterloo Innovation Park Emergency Phone Link
    columnSuffix: khkzsuid
    contentColumnType: text
    fieldGroup: null
    handle: wipEmergencyPhoneLink
    instructions: null
    name: 'Waterloo Innovation Park Emergency Phone Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b4a72afd-9824-4711-8c7c-654a73ab4125: # Waterloo Innovation Park Inquiries Phone Display 2
    columnSuffix: ieyczdcf
    contentColumnType: text
    fieldGroup: null
    handle: wipInquiriesPhoneDisplay2
    instructions: null
    name: 'Waterloo Innovation Park Inquiries Phone Display 2'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b87bb998-aa92-42fc-aee9-1adb2c624a30: # The Link Address
    columnSuffix: heaaoxqp
    contentColumnType: text
    fieldGroup: null
    handle: theLinkAddress
    instructions: null
    name: 'The Link Address'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cb6d8f3b-a601-41e8-8045-6ab67f0d37b8: # Waterloo Innovation Park Address
    columnSuffix: uwlicxrp
    contentColumnType: text
    fieldGroup: null
    handle: wipAddress
    instructions: null
    name: 'Waterloo Innovation Park Address'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d970ca81-be2c-4ab3-a6d4-156dafe345fe: # Waterloo Innovation Park Inquiries Phone Link
    columnSuffix: eabuymqv
    contentColumnType: text
    fieldGroup: null
    handle: wipInquiriesPhoneLink
    instructions: null
    name: 'Waterloo Innovation Park Inquiries Phone Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d4461882-7624-4f6f-ac6c-c06ea4a4689d: # The Link Email Link
    columnSuffix: kfxghkmm
    contentColumnType: text
    fieldGroup: null
    handle: theLinkEmailLink
    instructions: null
    name: 'The Link Email Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e7c7e219-044d-4f4e-813d-a85552002327: # Waterloo Innovation Park Contact Message
    columnSuffix: xpsrufwc
    contentColumnType: text
    fieldGroup: null
    handle: wipContactMessage
    instructions: null
    name: 'Waterloo Innovation Park Contact Message'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e63c55f2-78e4-45cc-9bd8-445b5d5b071a: # Waterloo Innovation Park Inquiries Phone Display
    columnSuffix: uvzjvxpk
    contentColumnType: text
    fieldGroup: null
    handle: wipInquiriesPhoneDisplay
    instructions: null
    name: 'Waterloo Innovation Park Inquiries Phone Display'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  faa07140-e5cb-4752-9790-0260ba2b62da: # Waterloo Innovation Park Leasing Phone Display
    columnSuffix: zwxyzkqj
    contentColumnType: text
    fieldGroup: null
    handle: wipLeasingPhoneDisplay
    instructions: null
    name: 'Waterloo Innovation Park Leasing Phone Display'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fbccfcff-4fb4-431b-99a0-3bf93c927097: # Waterloo Innovation Park Leasing Phone Link
    columnSuffix: pywqauld
    contentColumnType: text
    fieldGroup: null
    handle: wipLeasingPhoneLink
    instructions: null
    name: 'Waterloo Innovation Park Leasing Phone Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contactDetails
name: 'Contact Details'
sortOrder: 18
