field: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
fieldLayouts:
  2c4b262a-98b7-45d6-a7cb-aa65c4e33c2c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8d83305-ed06-4c80-971d-0a649f1c0cff # Heading - Card 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3442b1bf-884c-4017-914f-b5bbb88b07a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c5be844-5334-4801-a2b8-28db8751a258 # Call-to-action - Card 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01d2c966-1072-47ec-8622-34f416bb8134
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 300367d4-d29d-4580-a797-6140fdfba101 # Image - Card 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78a2fb9c-bf15-4055-be7a-98a660fe542f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 745a1ded-59d8-4b2d-935c-2ed9da87fb59 # Map Embed - Card 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffbfc054-0298-47f9-b4cc-97654780c117
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd6f9a8d-814f-456d-8fc3-d60933f1ed0a # Heading - Card 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8225914-a46a-4019-b0f8-93f21cc4914a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f76199d1-0bdf-4450-81d3-d2aefa255f91 # Call-to-action - Card 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e4a42aa-e5f0-4066-aad3-7dff8da37694
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7185e0e8-2762-4d5d-b963-5a2f92ca4f6e # Image - Card 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bafa1745-7fb1-4d7b-b6e6-2e990eebb9a4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 08a761d2-9bd6-49b9-92c0-3e5534c97af2
        userCondition: null
fields:
  5c5be844-5334-4801-a2b8-28db8751a258: # Call-to-action - Card 1
    columnSuffix: dtpdhixq
    contentColumnType: text
    fieldGroup: null
    handle: cardCta
    instructions: null
    name: 'Call-to-action - Card 1'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  745a1ded-59d8-4b2d-935c-2ed9da87fb59: # Map Embed - Card 1
    columnSuffix: vdverwyt
    contentColumnType: text
    fieldGroup: null
    handle: mapEmbedCard1
    instructions: 'If populated, this will take precedence over the image for card 1'
    name: 'Map Embed - Card 1'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7185e0e8-2762-4d5d-b963-5a2f92ca4f6e: # Image - Card 2
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardImage2
    instructions: null
    name: 'Image - Card 2'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  300367d4-d29d-4580-a797-6140fdfba101: # Image - Card 1
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardImage
    instructions: null
    name: 'Image - Card 1'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a8d83305-ed06-4c80-971d-0a649f1c0cff: # Heading - Card 1
    columnSuffix: xivskmhs
    contentColumnType: text
    fieldGroup: null
    handle: cardHeading
    instructions: null
    name: 'Heading - Card 1'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dd6f9a8d-814f-456d-8fc3-d60933f1ed0a: # Heading - Card 2
    columnSuffix: tmvnkqho
    contentColumnType: text
    fieldGroup: null
    handle: cardHeading2
    instructions: null
    name: 'Heading - Card 2'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f76199d1-0bdf-4450-81d3-d2aefa255f91: # Call-to-action - Card 2
    columnSuffix: potwvsnf
    contentColumnType: text
    fieldGroup: null
    handle: cardCta2
    instructions: null
    name: 'Call-to-action - Card 2'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: ctaCards
name: 'Call To Action Cards'
sortOrder: 13
