field: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
fieldLayouts:
  16de3526-8d8e-4bbb-a5ec-a0884ecd4287:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d40fc290-3cb8-4974-b1e9-4ab5e279ce4a # Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82e9d865-c25b-418d-a580-11174784815d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 710f40a4-9595-439f-ba53-b0995864d7ca # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d79e9c0-e862-472d-ae9f-3db7042d6cde
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a9c949f-a4f8-46c9-b908-e0fba1e95286 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f1a7065-4383-4418-bc88-57d9c11205e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d0605aa-2db0-476d-a8cd-009b9efc4eeb # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1a58df3-23db-4361-892e-fc2895026fdb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e1d40f9-bcc2-45e5-a18f-9a845b7988db # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0854b0e5-79a2-495f-9761-ba428d61a894
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56c3c12e-76ff-4b2e-8e3c-382ad3315b5b # Section Content Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca65b546-4cdb-4fe4-a3f7-4848f89c1050
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e12bca54-c3b9-4ba0-9641-31e98bd18527 # Remove padding top?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d19c3210-04e9-4626-b830-3fd278a1e1e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ed5c58c3-40e2-49f6-b6b9-7e2572a74f7f
        userCondition: null
fields:
  0d0605aa-2db0-476d-a8cd-009b9efc4eeb: # Button Link
    columnSuffix: ndoucoss
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonHref
    instructions: null
    name: 'Button Link'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  3e1d40f9-bcc2-45e5-a18f-9a845b7988db: # Button Text
    columnSuffix: akkxszqq
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8a9c949f-a4f8-46c9-b908-e0fba1e95286: # Summary
    columnSuffix: ricsanij
    contentColumnType: text
    fieldGroup: null
    handle: summary
    instructions: null
    name: Summary
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  56c3c12e-76ff-4b2e-8e3c-382ad3315b5b: # Section Content Location
    columnSuffix: skejqriv
    contentColumnType: string
    fieldGroup: null
    handle: contentLocation
    instructions: null
    name: 'Section Content Location'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - none
            -
              - value
              - none
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Top
            -
              - value
              - top
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Bottom
            -
              - value
              - bottom
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  710f40a4-9595-439f-ba53-b0995864d7ca: # Heading
    columnSuffix: rbfdraxs
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d40fc290-3cb8-4974-b1e9-4ab5e279ce4a: # Limit
    columnSuffix: hviirdid
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: null
    name: Limit
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  e12bca54-c3b9-4ba0-9641-31e98bd18527: # Remove padding top?
    columnSuffix: inxoydnv
    contentColumnType: boolean
    fieldGroup: null
    handle: topPadding
    instructions: 'Optionally remove the top whitespace from the section.'
    name: 'Remove padding top?'
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: eventSlider
name: 'Event Slider'
sortOrder: 10
