field: b480097d-88f7-49e8-a74a-530aaf07fb0a # Annual Events
fieldLayouts:
  d36e9820-9e07-4046-a320-d127a7b06416:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 13ddc265-7d77-4ac9-b0d0-e35357fb61cb # Item Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16a07d46-08f8-44e2-a417-a7cb8c0cf8fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b5a5788-43ee-4012-ba1a-ed2b73b8bbfb # ItemSVG
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d0ee733-1198-4ce3-875f-5a692ff8d9f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f243fa33-cb56-47f1-a1c2-a1a477cc6307 # Item Details
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f9ccda6-3fbe-4dda-83ce-3ab280095432
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 46a8a927-886e-4807-ba02-eeebaf3be2d7
        userCondition: null
fields:
  4b5a5788-43ee-4012-ba1a-ed2b73b8bbfb: # ItemSVG
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemSvg
    instructions: null
    name: ItemSVG
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  13ddc265-7d77-4ac9-b0d0-e35357fb61cb: # Item Title
    columnSuffix: mhsqctvk
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: null
    name: 'Item Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f243fa33-cb56-47f1-a1c2-a1a477cc6307: # Item Details
    columnSuffix: hwwxfeyw
    contentColumnType: text
    fieldGroup: null
    handle: itemDetails
    instructions: null
    name: 'Item Details'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: item
name: Item
sortOrder: 1
