field: e2190436-67a6-4e37-bc3b-b0e52e23f9e7 # Gallery Items
fieldLayouts:
  bdeb5eb1-bd0a-403b-96de-dc1e78862a8d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 903cf4e1-deba-4181-804b-66520fe03fdc # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f767ddde-2d3a-4548-a13c-eca6d4239f86
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8b4a8b9-f098-48a3-b3c9-9149a1f3d3e7 # Art Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fdb3803-1938-4214-9e1d-03618955c188
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb1ecf4b-0473-4929-80c1-830b574c0c48 # Cost
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15df6585-1529-4513-bd3d-07eb42dc0b9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0493ce96-a299-4502-9f34-15fe3bebbdaa # Artist
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 304707dd-2700-48c1-8931-3f6c709446cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3e466e4-7126-4d1b-ae44-65f099f3487e # Year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f3c37b1-6f46-43da-a110-e08bc821aea3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: baa2eb32-a191-474e-b7da-50764f46b1e5 # Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85ecaee3-f0ef-4c11-92ea-b613ab968c6d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6cde26e3-33c6-4120-b1df-67acc27a91c1
        userCondition: null
fields:
  0493ce96-a299-4502-9f34-15fe3bebbdaa: # Artist
    columnSuffix: egedwktu
    contentColumnType: text
    fieldGroup: null
    handle: artist
    instructions: null
    name: Artist
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  903cf4e1-deba-4181-804b-66520fe03fdc: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:3906dce9-9071-435f-96fc-05a701d81f46' # Exhibition Photos
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:3906dce9-9071-435f-96fc-05a701d81f46' # Exhibition Photos
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a8b4a8b9-f098-48a3-b3c9-9149a1f3d3e7: # Art Name
    columnSuffix: fvfnzeud
    contentColumnType: text
    fieldGroup: null
    handle: artName
    instructions: null
    name: 'Art Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b3e466e4-7126-4d1b-ae44-65f099f3487e: # Year
    columnSuffix: hhfqtwpa
    contentColumnType: text
    fieldGroup: null
    handle: year
    instructions: null
    name: Year
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  baa2eb32-a191-474e-b7da-50764f46b1e5: # Info
    columnSuffix: akufmake
    contentColumnType: text
    fieldGroup: null
    handle: info
    instructions: null
    name: Info
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cb1ecf4b-0473-4929-80c1-830b574c0c48: # Cost
    columnSuffix: rakmnugu
    contentColumnType: integer(10)
    fieldGroup: null
    handle: cost
    instructions: null
    name: Cost
    searchable: false
    settings:
      currency: USD
      defaultValue: null
      max: null
      min: 0
      showCurrency: true
      size: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Money
handle: item
name: Item
sortOrder: 1
