field: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
fieldLayouts:
  2d3ba72f-d2e8-4214-ab29-4878f3133c52:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3793567-0e66-4d19-ba2b-740920371872 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a9294b2-f07b-42bf-82a2-619170b181fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a51d302d-a33f-4abc-8ffe-bbaf14e67455 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47468338-1b32-4e19-9e51-abebfd01a1dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f7e10c1-d4ec-4f06-a166-d8de4344f974 # Iframe Embed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43481fa8-24fe-4e4e-8a3e-a73e76d3c40e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28e33f30-0531-4723-b2ac-1abf27a1bde7 # Directions Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61734bcf-0fd4-4d0d-9dda-45f91eaacc97
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f6ffffa-f5e2-44c6-8221-ffd6a0555f9f # Map Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 208d679b-5f58-4282-a164-51ebf9da6185
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 60a54b19-a2b2-454c-9726-c413cd959289
        userCondition: null
fields:
  2f7e10c1-d4ec-4f06-a166-d8de4344f974: # Iframe Embed
    columnSuffix: hctesasg
    contentColumnType: text
    fieldGroup: null
    handle: iframeEmbed
    instructions: null
    name: 'Iframe Embed'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6f6ffffa-f5e2-44c6-8221-ffd6a0555f9f: # Map Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: mapImage
    instructions: null
    name: 'Map Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  28e33f30-0531-4723-b2ac-1abf27a1bde7: # Directions Link
    columnSuffix: boszafkx
    contentColumnType: text
    fieldGroup: null
    handle: directionsLink
    instructions: null
    name: 'Directions Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a51d302d-a33f-4abc-8ffe-bbaf14e67455: # Summary
    columnSuffix: zcmxonsv
    contentColumnType: text
    fieldGroup: null
    handle: summary
    instructions: null
    name: Summary
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 10
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e3793567-0e66-4d19-ba2b-740920371872: # Heading
    columnSuffix: dqyjcnvs
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: map
name: Map
sortOrder: 12
