field: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
fieldLayouts:
  ab06e501-e2e5-45f1-abce-183c17fe3b75:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 16a6044c-5238-4f14-8aad-ce2d5bf16347 # Page Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34a34cd3-9562-4741-9b80-913c674ce451
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a8e7ac8e-4881-4a74-a128-efe7e520c828
        userCondition: null
fields:
  16a6044c-5238-4f14-8aad-ce2d5bf16347: # Page Summary
    columnSuffix: wyxvjuwv
    contentColumnType: text
    fieldGroup: null
    handle: pageSummary
    instructions: null
    name: 'Page Summary'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: pageIntro
name: 'Page Intro'
sortOrder: 7
