field: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
fieldLayouts:
  28d5d6f2-f419-4423-89e4-47013db3d8dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e7435167-064b-48ec-953f-a5da23d3edda # Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23eda347-b5a5-4e94-9166-f8e4af192e00
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65896fb7-8b55-421c-b95c-d6dc099117a5
        userCondition: null
fields:
  e7435167-064b-48ec-953f-a5da23d3edda: # Limit
    columnSuffix: hhlwigsa
    contentColumnType: integer(10)
    fieldGroup: null
    handle: limit
    instructions: null
    name: Limit
    searchable: false
    settings:
      decimals: 0
      defaultValue: 12
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: pastExhibitRollup
name: 'Past Exhibits Rollup'
sortOrder: 17
