field: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
fieldLayouts:
  a3ac63ad-8d19-4075-9b2e-e247641c30c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 433605c5-e0d4-4a9c-a940-6614863fff4a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61664b2b-6d33-4a72-8608-ea22b9d033bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 284d17e3-f78c-42b0-a5d0-6cba8be9f1d0 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7c99721-24b9-4da1-95b8-8656b3cce08f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 667c38fa-fdd2-4239-908a-d5f2551515a4 # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a589f6f-a5cc-41d6-9447-6b0a1367fca9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6aa515b4-55f0-4be2-811d-a261d6ff4532 # Main Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2f0a543-3000-4954-acf9-74bae81b0d85
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e760a300-2ccc-4626-9448-8cd0009bfa9c # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7930b31c-2aec-4a44-8de4-60b0f9321685
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8adcca86-f9ed-44da-a316-c88c7fef98d5
        userCondition: null
fields:
  6aa515b4-55f0-4be2-811d-a261d6ff4532: # Main Content
    columnSuffix: vrqcuunf
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: 'Main Content'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  284d17e3-f78c-42b0-a5d0-6cba8be9f1d0: # Button Text
    columnSuffix: benevmuz
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  667c38fa-fdd2-4239-908a-d5f2551515a4: # Button Link
    columnSuffix: uiizaatt
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonHref
    instructions: null
    name: 'Button Link'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  433605c5-e0d4-4a9c-a940-6614863fff4a: # Heading
    columnSuffix: vneweipf
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e760a300-2ccc-4626-9448-8cd0009bfa9c: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 3
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:9cfc771b-b401-4434-bbd3-e0e94c877314' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: textColumnsWith3Images
name: '2 Text Columns With 3 Images'
sortOrder: 14
