app: waterlooip
ssh_url: waterlooip@deploy.us1.frbit.com
git_remote: waterlooip/master
before:
    code/up: {  }
after:
    code/down:
        - 'php craft migrate/all'
        - 'php craft project-config/apply'
