fieldLayouts:
  44eefc40-e6d2-4005-93f2-60e163f7e545:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3bf2a346-859c-41b9-9528-9430ab9a2f91
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cadde915-c6fb-46a6-a77a-6fafdcb4e322 # Page Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95324875-51ce-469f-991a-b168a65d40f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f949aa8-1797-4b29-b437-d531558d65c7 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38e17dbc-e022-4a20-94dd-fc6478f86b75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec1c3db1-02e8-4fdd-b5ad-f3f9bd90e586 # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5f68876-73d8-4e0b-98e0-c06705d111e0
            userCondition: null
            warning: null
            width: 100
        name: 'Page Intro'
        uid: 7db536ab-5c65-45b2-bf7d-182e006ca1d2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 396d0599-4a5e-442d-aa43-661d78e9111a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e77ae473-a86b-4a41-a7c8-9388d460bab0
        userCondition: null
handle: about
hasTitleField: true
name: About
section: ee51cfa4-ec13-4103-bf30-68e7c1b63ac5 # About
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
