fieldLayouts:
  582b2fe1-9686-4c14-9d94-68cd847b1238:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9387a048-0016-40b3-835c-ff12343a9515
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cadde915-c6fb-46a6-a77a-6fafdcb4e322 # Page Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a12e3c85-e532-434f-8fc6-ff212e1199be
            userCondition: null
            warning: null
            width: 100
        name: 'Page Intro'
        uid: 5da9591a-e127-4c34-b031-551d3c121c64
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cf5ded5-8430-4825-8ec6-dc165d9a8b90
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c1e7755-9eee-4e46-a287-dd2be0ce0373
        userCondition: null
handle: bookPrivateEvent
hasTitleField: true
name: 'Book Private Event'
section: 86bf8d52-4937-4435-86ec-d080ca4fd0d7 # Book Private Event
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
