fieldLayouts:
  582b2fe1-9686-4c14-9d94-68cd847b1238:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9387a048-0016-40b3-835c-ff12343a9515
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37175b69-3644-4f1e-a348-e82fd2565057 # Property Manager Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82e97c98-986a-48ad-9f61-afcb29a930ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd3a546e-11a2-4fd7-a835-04974a2d24ff # Booking Contact Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ee1f930-bdda-4beb-bc8b-c455efb53629
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e724cd6-994a-493e-945a-c6dadbff9837 # Property Manager Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bc60c87-c2d0-41cb-8d8f-c2faa1ea455b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79a345ab-2e14-443b-b9f2-e4caeb12f9a2 # Booking Form Recipient Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f851603a-6508-408a-844d-c157e05a6892
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5da9591a-e127-4c34-b031-551d3c121c64
        userCondition: null
handle: bookPrivateEvent
hasTitleField: true
name: 'Book Private Event'
section: 86bf8d52-4937-4435-86ec-d080ca4fd0d7 # Book Private Event
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
