fieldLayouts:
  582b2fe1-9686-4c14-9d94-68cd847b1238:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9387a048-0016-40b3-835c-ff12343a9515
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56b20bcf-23a6-4b09-ab8c-00a3d69c54c1 # Page Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8f66742-85d0-457c-ac9a-b5746eaaa7e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e724cd6-994a-493e-945a-c6dadbff9837 # Property Manager Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7dbea73-fa14-4f98-bac0-4246bb9834b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37175b69-3644-4f1e-a348-e82fd2565057 # Property Manager Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c1b620b-5063-4837-8a7e-369fe30d7fe2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5f8cb9f8-3c0c-4264-8031-dbfe5b65434a # Property Manager Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a87027f-cdc8-490b-83be-f31ad9409faf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8cef2e04-1901-44a9-bf0c-0f320e8760ba # Property Manager Phone Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e08e8dd-1d10-4341-8806-13447be8666d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b29d046d-03e7-4eb8-9248-7c870d157e78 # Property Manager Phone Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ce43164-77bb-4b1e-aa7d-89a829190d3c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5da9591a-e127-4c34-b031-551d3c121c64
        userCondition: null
handle: bookPrivateEvent
hasTitleField: true
name: 'Book Private Event'
section: 86bf8d52-4937-4435-86ec-d080ca4fd0d7 # Book Private Event
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
