fieldLayouts:
  1cc3ea1e-0a07-4620-8642-a7ce5b5ae367:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7dd75d2a-bc5d-46b6-aec3-5d1558b8a506
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 74fd3c95-bfef-47aa-b709-c4f38b3c9bcd
        userCondition: null
handle: calendarMonth
hasTitleField: false
name: 'Calendar Month'
section: 07b6aedb-1dae-4e10-97cd-ccd64792dd3c # Calendar Month
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
