fieldLayouts:
  7a3e3556-e122-4e9d-be98-513e4c567a83:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8393d267-ab92-44f9-9afe-4a627b86399d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e8e63f2-7d74-4008-adde-a4fa181488e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 47b5e67e-c01b-4de1-94dd-e0501368e229 # Artist
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c2a0a7d-8b39-42ca-9899-d218b95abfc3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f95f803-ea1a-450d-856b-d4604d326a97 # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6304b565-95e8-4dd9-a2d3-fa351cb125ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3653102e-75a7-411d-bfbf-ea9d4de077f4 # Rollup Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4bc0457-f948-4b05-991e-ba4552860231
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 34e247a1-8be7-4932-a481-cfa735abdba3 # Exhibition Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ccabd7d-83b8-46e9-859b-32857a75dbb8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a9616099-3fb4-4a1f-876a-532a708871cb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e2190436-67a6-4e37-bc3b-b0e52e23f9e7 # Gallery Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04d4cdc9-6897-432a-bace-ed880d82894f
            userCondition: null
            warning: null
            width: 100
        name: 'Gallery Items'
        uid: d53a8d66-3a94-401c-bf2e-30a7a6fa63d6
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: 506955ce-fa3f-407f-9b5c-f7d79b9b1e42 # Exhibits
sortOrder: 1
titleFormat: '{entry.name | raw }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
