fieldLayouts:
  56ce38c1-4c36-4f61-bb03-b60232a56b01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d06f856c-0609-4701-8c33-cd0e1a203df6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 684e5d7e-d5af-4cb2-9ee1-9833cee409d6
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 9f2bc7d7-ce7d-4a3e-8704-3b608e00d2d6 # Properties
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
