fieldLayouts:
  665ef582-a871-4020-916d-60c365001ed1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 55464e13-e372-45f5-a985-19baaa8e61d7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4376fc28-a7c8-4264-ae89-8fd01d231075 # Current Featured Exhibit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b7c9803-612f-4dfd-b348-a5984ed7b3a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8eb6d4e-c784-4630-9ee0-b7a90c716409
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0768547c-2f2e-4f5d-a30b-6711317456e6
        userCondition: null
handle: featuredExhibit
hasTitleField: false
name: 'Featured Exhibit'
section: d71f2b99-711c-44b6-ade1-1f5ed6237842 # Featured Exhibit
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
