fieldLayouts:
  c830b285-2e15-431e-8fa3-5c2187b9db50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 67746eb7-7160-4f3f-a1d3-c243eeb29413
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31aa51d3-2c41-4a98-8464-95f377cc4f07 # Lease Managers Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 505845c2-8729-4ab9-aacd-6722286252a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 52d8ea63-1195-47df-9693-9e83d7049cd2 # Lease Managers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 371d4c2f-8fa5-464a-8231-42a39397f8cd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3ccf02e7-f613-44fe-b27e-7e7387f2e9fa
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 771b1ebb-9bc3-4a71-9969-b7e5f1020bb7 # Property Item
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01bcaf95-3066-425c-9d92-525635290539
            userCondition: null
            warning: null
            width: 100
        name: Properties
        uid: c6c250e6-ba47-423b-a29b-9eb02505aa94
        userCondition: null
handle: lease
hasTitleField: true
name: 'Lease now'
section: 7d4ea53b-345f-4ffd-aeb1-c3be93482fcb # Lease now
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
