fieldLayouts:
  62026505-2148-4178-8f8f-b9d329f81599:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ba6f9d21-1013-4cbe-ab1c-7a9b8ea823a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 733dbb70-0c0d-45c2-b33a-601f58fbaecf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2909a920-4272-44f4-adcc-9deaaa65ceba
        userCondition: null
handle: pastExhibit
hasTitleField: false
name: 'Past Exhibit'
section: 8c002f04-e95f-478c-924a-13bda79698f8 # Past Exhibit
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
