fieldLayouts:
  3b7b6aa5-04f1-4476-9775-4ff89b5737f8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 096f7cac-788f-4c34-a234-a43fa153a512
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cadde915-c6fb-46a6-a77a-6fafdcb4e322 # Page Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6296df1-4e4e-488f-b024-394767e5e0b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f949aa8-1797-4b29-b437-d531558d65c7 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c6db9f4-bbd1-480b-aa9f-ba3d36705eeb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec1c3db1-02e8-4fdd-b5ad-f3f9bd90e586 # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57d71c25-7107-49c8-aa59-2a95c73ba37d
            userCondition: null
            warning: null
            width: 100
        name: 'Page Intro'
        uid: 8f9203fb-5387-492a-af4d-66d4dc65353e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 745cf2fc-6457-41df-a21e-131f47a52823 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3570a13c-a035-4e51-aa09-b39d1b4a1437
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 69937934-238e-4e7f-8423-ed689637a578
        userCondition: null
handle: theLink
hasTitleField: true
name: 'The Link'
section: 92500a08-4b00-4235-be91-e4a8d210dd0d # The Link
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
