allowRepeatingEvents: true
color: '#72a34d'
description: ''
descriptionFieldHandle: '0'
fieldLayout:
  tabs:
    -
      elementCondition: null
      elements:
        -
          elementCondition: null
          fieldUid: b19956e7-f23d-451e-93c0-712acc2c2b9a # Event Description
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 17afd8fd-4616-438a-8fa0-99aff8cf7ead
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 169eb7a3-ac32-4f0f-afd8-eb8b92803b1b # Event Image
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: dd42bd63-ef6e-45da-b4e0-e7f3bece35cc
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          heading: 'Event Slider'
          type: craft\fieldlayoutelements\Heading
          uid: 68fc1dca-1b5d-43e9-a5b3-1e05a5718129
          userCondition: null
        -
          elementCondition: null
          fieldUid: 9d0ece9f-df15-4593-94b1-66eb90467427 # Event Slider Poster Image
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: dae4753c-f57b-4b22-81a0-619107db152c
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 809ce6db-5c77-4e75-9eb9-1d42abe1485b # Event Slider Details
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 5a791946-29e0-4bcf-9db4-4ddce9bdcfb7
          userCondition: null
          warning: null
          width: 100
      name: 'Event Metadata'
      uid: b0b4d63e-d838-41ed-bced-385120df95cd
      userCondition: null
  uid: 94607e83-2a5b-41ee-96df-fd534447cc9f
handle: artEvents
hasTitleField: true
icsHash: null
icsTimezone: floating
locationFieldHandle: '0'
name: 'Art Events'
siteSettings:
  195500d8-db97-4f04-bda0-671df20451a9:
    enabledByDefault: true
    hasUrls: false
    siteId: 402b359e-759c-4938-b279-b9a22b2c6d6a # Waterloo Innovation Park
    template: null
    uriFormat: null
titleFormat: ''
titleLabel: Title
titleTranslationKeyFormat: ''
titleTranslationMethod: none
