fieldLayouts:
  17025839-b91b-4427-ac34-586e51b605f6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 59dd4244-25bd-4965-8b5a-660f6a22354b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6405d649-c5c7-451a-b154-93b7dcde1df4
        userCondition: null
fs: instagram
handle: instagram
name: Instagram
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
