columnSuffix: rvsmkrno
contentColumnType: text
fieldGroup: 21bdf77a-7ef8-4373-91e0-b6f8b61e6459 # Events
handle: description
instructions: null
name: 'Event Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 6
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
