columnSuffix: zhoqywes
contentColumnType: string(200)
fieldGroup: 21bdf77a-7ef8-4373-91e0-b6f8b61e6459 # Events
handle: eventSliderDetails
instructions: null
name: 'Event Slider Details'
searchable: false
settings:
  byteLimit: null
  charLimit: 50
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
