columnSuffix: eyljfrrr
contentColumnType: string(255)
fieldGroup: 89833881-16ce-4ec4-abfd-1f352dc99fd8 # Common
handle: facebook
instructions: null
name: Facebook
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
