dateModified: 1680018400
email:
  fromEmail: mr.coru@gmail.com
  fromName: 'Waterloo Innovation Park'
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  exhibitionPhotos:
    hasUrls: true
    name: 'Exhibition Photos'
    settings:
      path: '@webroot/exhibition-photos'
    type: craft\fs\Local
    url: '@web/exhibition-photos'
  instagram:
    hasUrls: true
    name: Instagram
    settings:
      path: '@webroot/instagram'
    type: craft\fs\Local
    url: '@web/instagram'
  leasing:
    hasUrls: true
    name: Leasing
    settings:
      path: '@webroot/leasing'
    type: craft\fs\Local
    url: '@web/leasing'
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@web/uploads'
meta:
  __names__:
    0afdac73-846a-4985-a071-851fed756ca9: 'Button Text' # Button Text
    0b9c054a-9bbd-4547-b554-70bfd7142228: 'Waterloo Innovation Park' # Waterloo Innovation Park
    0d01ac2a-6f7f-4925-8c97-10d917e18c84: Title # Title
    0d0605aa-2db0-476d-a8cd-009b9efc4eeb: 'Button Link' # Button Link
    0d3d2425-6d71-474f-9ff8-bbaa45b837c5: 'Hero Panel (Dark)' # Hero Panel (Dark)
    1da30993-295b-40b9-aab0-24e5a9812929: 'Panel Subheading' # Panel Subheading
    1f0b8178-c969-454d-94a7-ae7d3f373f86: Subheading # Subheading
    2a874f96-2ff5-4132-815e-da2d51664308: 'Book Private Event' # Book Private Event
    2e724cd6-994a-493e-945a-c6dadbff9837: 'Property Manager Image' # Property Manager Image
    2f95f803-ea1a-450d-856b-d4604d326a97: Date # Date
    3ccea268-3f4e-423c-9d53-fa8a781f9b58: item # item
    3e1d40f9-bcc2-45e5-a18f-9a845b7988db: 'Button Text' # Button Text
    4b4b1468-382a-43a9-a954-3816f65567a2: Heading # Heading
    4bf1c6a2-b8b6-48fb-bdac-d9e5804d9ab6: 'Button Text' # Button Text
    4df73862-66da-4140-8eac-6eeb31f2aa4c: 'Button Link' # Button Link
    04e5c194-9ae4-47b7-984b-0892ca576ec9: Images # Images
    5b4ec8f1-aa69-4807-871b-8e4f533f4440: 'Lease now' # Lease now
    5bb2582c-1b3b-4a0a-b234-64558f60c9a9: Image # Image
    5e5cfcfd-2853-4707-b73e-471efcd57cc8: Default # Default
    5e672526-c38e-4fdc-b248-363c3c83ef20: Subject # Subject
    5f8cb9f8-3c0c-4264-8031-dbfe5b65434a: 'Property Manager Email' # Property Manager Email
    6a083dd0-c3a0-40c7-a437-2c5c4610fa50: Heading # Heading
    6dc1ef68-7606-4254-8f3e-ab00a4a0b146: 'Button Link' # Button Link
    6f01e9c8-9af2-4589-8d81-a9ed56130cc9: 'Job Title' # Job Title
    6f949aa8-1797-4b29-b437-d531558d65c7: 'Button Text' # Button Text
    7b3301be-ed48-400a-a679-7b61d6a9fab8: Path # Path
    7bc74160-416f-46f7-9447-6f6fad7b93ec: 'Page Heading' # Page Heading
    7c0905c7-cf97-4e6a-85aa-2dec1a0f13e5: 'Button Text' # Button Text
    7c65acbe-cf3a-4d9d-8c29-198033c701a3: Instagram # Instagram
    7d4ea53b-345f-4ffd-aeb1-c3be93482fcb: 'Lease now' # Lease now
    8a9c949f-a4f8-46c9-b908-e0fba1e95286: Summary # Summary
    8af21ea5-8ed7-451b-9561-65de6890a24a: Events # Events
    8c002f04-e95f-478c-924a-13bda79698f8: 'Past Exhibit' # Past Exhibit
    8c1501f8-32b3-4150-91bc-23f988eb98e5: About # About
    8cef2e04-1901-44a9-bf0c-0f320e8760ba: 'Property Manager Phone Display' # Property Manager Phone Display
    9c87d94e-3edf-4ac7-8d8b-be65d21b54e5: 'Site Navigation' # Site Navigation
    09cde05d-5606-478a-8ab0-d9a6a607d414: Contact # Contact
    9cfc771b-b401-4434-bbd3-e0e94c877314: Uploads # Uploads
    9d0ece9f-df15-4593-94b1-66eb90467427: 'Event Slider Poster Image' # Event Slider Poster Image
    9d42013b-11c6-42cf-b45b-fa037c8bcaba: Title # Title
    9f2bc7d7-ce7d-4a3e-8704-3b608e00d2d6: Properties # Properties
    15b5c3b8-1bf0-499c-84f7-3a6c39f656d1: 'Phone Link' # Phone Link
    16a6044c-5238-4f14-8aad-ce2d5bf16347: 'Page Summary' # Page Summary
    21bdf77a-7ef8-4373-91e0-b6f8b61e6459: Events # Events
    24a64e3b-2ad3-479e-89dc-1c16e57368ac: Booking # Booking
    25c1ea66-8095-4f2a-971e-611b21bba3aa: Item # Item
    26baa828-2510-4546-ab8a-4866ca224fa2: 'Featured Exhibit' # Featured Exhibit
    31aa51d3-2c41-4a98-8464-95f377cc4f07: 'Lease Managers Heading' # Lease Managers Heading
    34e247a1-8be7-4932-a481-cfa735abdba3: 'Exhibition Summary' # Exhibition Summary
    36e3ae0f-08a5-4193-af58-4ed32c350d94: Image # Image
    42a3ddcd-d834-49a3-a79e-21c3f11a6ab6: 'Image panel' # Image panel
    45e37949-8c8b-424e-8d3e-8d4b606ed084: Item # Item
    47b5e67e-c01b-4de1-94dd-e0501368e229: Artist # Artist
    51f09ffd-ffd8-4abf-9a71-5bbb77aac42b: 'Event Slider' # Event Slider
    52ac9c9a-5d73-4e34-b24e-edf09a5a6b47: Default # Default
    52d8ea63-1195-47df-9693-9e83d7049cd2: 'Lease Managers' # Lease Managers
    56c3c12e-76ff-4b2e-8e3c-382ad3315b5b: 'Section Content Location' # Section Content Location
    075e886a-d174-424c-938b-98d8a9b420ae: 'Image Slider' # Image Slider
    78ee6ec1-b0de-4912-a9f9-ced7e4c1646e: 'Call To Action Panel' # Call To Action Panel
    79e72fa5-51bb-408b-b0b7-ebd8acbbe7b2: 'Panel Title' # Panel Title
    86bf8d52-4937-4435-86ec-d080ca4fd0d7: 'Book Private Event' # Book Private Event
    87f60dce-cac6-4d30-90ef-a6a2040f4d0d: 'Post Count' # Post Count
    95ecac41-0668-4b7c-a8ac-8ec14d07b5af: Subject # Subject
    114dbb25-d74a-43df-9136-bbc8e4bdeaec: Content # Content
    169eb7a3-ac32-4f0f-afd8-eb8b92803b1b: 'Event Image' # Event Image
    220d125c-af88-4a55-9b6c-ddae8a634855: 'Content Panel' # Content Panel
    335c9bcd-5565-445e-a5cf-ed5a78aac5e7: 'Phone Display' # Phone Display
    354ce86f-294c-4c2e-a75a-be2deb8cb9d0: 'Page Heading' # Page Heading
    402b359e-759c-4938-b279-b9a22b2c6d6a: 'Waterloo Innovation Park' # Waterloo Innovation Park
    0493ce96-a299-4502-9f34-15fe3bebbdaa: Artist # Artist
    687cd2f1-06f5-4174-ab03-40daaa93ad90: 'Panel Title' # Panel Title
    703da12e-6c3e-477c-847b-e1a6b6953e8e: 'Property Name' # Property Name
    710f40a4-9595-439f-ba53-b0995864d7ca: Heading # Heading
    745cf2fc-6457-41df-a21e-131f47a52823: Content # Content
    750a3bea-3a7c-48b8-a453-41661ad274fa: 'Page Intro' # Page Intro
    771b1ebb-9bc3-4a71-9969-b7e5f1020bb7: 'Property Item' # Property Item
    809ce6db-5c77-4e75-9eb9-1d42abe1485b: 'Event Slider Details' # Event Slider Details
    903cf4e1-deba-4181-804b-66520fe03fdc: Image # Image
    959a923c-97d7-425f-baea-2a45e43116cf: 'Past Exhibit' # Past Exhibit
    1057c048-812f-4e87-b8f7-208e91e4c8fc: 'Button Text' # Button Text
    3906dce9-9071-435f-96fc-05a701d81f46: 'Exhibition Photos' # Exhibition Photos
    8267e525-8100-4ca9-9949-0677504ad351: email # email
    37175b69-3644-4f1e-a348-e82fd2565057: 'Property Manager Image Caption' # Property Manager Image Caption
    91458f3d-5347-4b47-a507-b691e9a17943: 'Navigation Items' # Navigation Items
    92500a08-4b00-4235-be91-e4a8d210dd0d: 'The Link' # The Link
    321611e0-0312-43af-a816-cd4e1af60c8f: 'Page Summary' # Page Summary
    465854cd-ce73-4e46-905e-7b925a0307e2: 'Exhibition Name' # Exhibition Name
    506955ce-fa3f-407f-9b5c-f7d79b9b1e42: Exhibits # Exhibits
    865120ee-347d-4344-95ec-61b32b775de0: Image # Image
    3653102e-75a7-411d-bfbf-ea9d4de077f4: 'Rollup Image' # Rollup Image
    5835035f-8ddd-4123-9120-309865e31c20: Default # Default
    36824767-1aa1-48a4-b266-8271b9035f52: Default # Default
    38134199-860e-4c8f-9bc6-d1e314e1884a: Leasing # Leasing
    87976032-e2ff-41bd-a53c-f0e4719793b4: Lease # Lease
    89833881-16ce-4ec4-abfd-1f352dc99fd8: Common # Common
    a8b4a8b9-f098-48a3-b3c9-9149a1f3d3e7: 'Art Name' # Art Name
    a702171c-dc55-496a-8140-10a53900a54a: 'Button Link' # Button Link
    ad3311a0-c30e-4a01-9405-46dc2bb50f43: 'Page Heading' # Page Heading
    afb98157-06dd-4f20-a32d-7759850afba2: 'Stat Holidays' # Stat Holidays
    b1c63a82-dac1-486f-a4f0-a01d8bd252d6: 'Image Vertical Position' # Image Vertical Position
    b3e466e4-7126-4d1b-ae44-65f099f3487e: Year # Year
    b5d074e4-1433-4ae3-85be-1e9d75889129: Calendar # Calendar
    b29d046d-03e7-4eb8-9248-7c870d157e78: 'Property Manager Phone Link' # Property Manager Phone Link
    b41afa41-893f-4b11-970e-c75f2431f0be: 'Learn More Link' # Learn More Link
    b19956e7-f23d-451e-93c0-712acc2c2b9a: 'Event Description' # Event Description
    baa2eb32-a191-474e-b7da-50764f46b1e5: Info # Info
    bc928e65-aad4-49d8-bfd2-4bc0a487d1ec: Details # Details
    c21e6094-c48b-4da7-b900-dd593e0d4125: Contact # Contact
    c84251ed-c157-4470-8a0b-fa532933274f: 'Hero Panel' # Hero Panel
    cb1ecf4b-0473-4929-80c1-830b574c0c48: Price # Price
    cb191950-443f-46b3-8914-5a71580972f5: 'Full Name' # Full Name
    cc67c156-422d-4f9e-be71-f3d094eb08e5: 'Art Gallery' # Art Gallery
    cc822dad-031d-4617-957a-65ba55d4ddb3: Instagram # Instagram
    ce352345-5dc4-4b53-a997-af7ff50bf606: Image # Image
    d3d92310-a896-45d2-810b-4f797da224ff: Summary # Summary
    d8a9784a-a8a3-4e31-9bf5-73aa7bd6f67c: Home # Home
    d40fc290-3cb8-4974-b1e9-4ab5e279ce4a: Limit # Limit
    d71f2b99-711c-44b6-ade1-1f5ed6237842: 'Featured Exhibit' # Featured Exhibit
    de802f05-8a3d-4fbd-99ee-3188ab50874c: Content # Content
    e12bca54-c3b9-4ba0-9641-31e98bd18527: 'Remove padding top?' # Remove padding top?
    e58e1829-76c2-476c-bf92-2f56e2f3900e: 'Button Link' # Button Link
    e2190436-67a6-4e37-bc3b-b0e52e23f9e7: 'Gallery Items' # Gallery Items
    ec1c3db1-02e8-4fdd-b5ad-f3f9bd90e586: 'Button Link' # Button Link
    ec147d51-bd50-4e6e-8f06-fdd1c19ad61a: 'The Link' # The Link
    ee51cfa4-ec13-4103-bf30-68e7c1b63ac5: About # About
    ef382811-26e2-4369-910e-ffa10df24c8b: Account # Account
    fbbb7b50-c55e-456d-9508-45a83c3219cb: Events # Events
    fd107921-d306-448f-ad1a-e7c2ef60913c: Home # Home
    fe4b113d-bf1c-4f36-806f-80cb15f3cac8: Title # Title
plugins:
  calendar:
    edition: lite
    enabled: true
    licenseKey: F4E23DFAOGINENN30SCZBG84
    schemaVersion: 4.0.2
    settings:
      allDay: false
      authoredEventEditOnly: ''
      defaultView: month
      demoBannerDisabled: true
      descriptionFieldHandle: null
      eventDuration: 60
      firstDayOfWeek: '0'
      guestAccess: null
      locationFieldHandle: null
      overlapThreshold: 5
      pluginName: null
      quickCreateEnabled: ''
      showDisabledEvents: ''
      showMiniCal: '1'
      timeFormat: auto
      timeInterval: 30
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of'
      prependSubject: ''
      successFlashMessage: 'Your message has been sent.'
      toEmail: corey.james.keller@gmail.com
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  instagramfeed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      dump: false
      instagramUser: thelink_innovationpark
      proxyKey: GPdOk5ibUUjHwnOn8fnY
      subpath: ''
      timeout: 10
      useProxy: true
      useVolume: true
      volume: instagram
  minical:
    edition: standard
    enabled: true
    licenseKey: 6J9WCW6A0HQH66SVHHDH4JDI
    schemaVersion: 1.0.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
system:
  edition: solo
  live: true
  name: 'Waterloo Innovation Park'
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: America/Toronto
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
