dateModified: 1690540112
email:
  fromEmail: donotreply@coloniatreuhand.com
  fromName: 'Waterloo Innovation Park'
  replyToEmail: null
  template: null
  transportSettings:
    apiKey: 01972b0752569ae74e84a14b1c3727e0
    apiSecret: 4ee0f2b6cfa15d4909619d12e37e8a66
  transportType: robuust\mailjet\MailjetAdapter
fs:
  exhibitionPhotos:
    hasUrls: true
    name: 'Exhibition Photos'
    settings:
      path: '@webroot/exhibition-photos'
    type: craft\fs\Local
    url: '@web/exhibition-photos'
  instagram:
    hasUrls: true
    name: Instagram
    settings:
      path: '@webroot/instagram'
    type: craft\fs\Local
    url: '@web/instagram'
  leasing:
    hasUrls: true
    name: Leasing
    settings:
      path: '@webroot/leasing'
    type: craft\fs\Local
    url: '@web/leasing'
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@web/uploads'
meta:
  __names__:
    0a351d7f-aa37-4d4b-8cbc-822719d3e521: 'The Link Email Display' # The Link Email Display
    0afdac73-846a-4985-a071-851fed756ca9: 'Button Text' # Button Text
    0b9c054a-9bbd-4547-b554-70bfd7142228: 'Waterloo Innovation Park' # Waterloo Innovation Park
    0d01ac2a-6f7f-4925-8c97-10d917e18c84: Title # Title
    0d0605aa-2db0-476d-a8cd-009b9efc4eeb: 'Button Link' # Button Link
    0d3d2425-6d71-474f-9ff8-bbaa45b837c5: 'Hero Panel' # Hero Panel
    0f2f856e-d16b-4407-9c3b-d0b013f21282: Twitter # Twitter
    1da30993-295b-40b9-aab0-24e5a9812929: 'Panel Subheading' # Panel Subheading
    1f0b8178-c969-454d-94a7-ae7d3f373f86: Subheading # Subheading
    2a874f96-2ff5-4132-815e-da2d51664308: 'Book Private Event' # Book Private Event
    2e724cd6-994a-493e-945a-c6dadbff9837: 'Property Manager Image' # Property Manager Image
    2f7e10c1-d4ec-4f06-a166-d8de4344f974: 'Iframe Embed' # Iframe Embed
    2f95f803-ea1a-450d-856b-d4604d326a97: Date # Date
    2fd8d280-fb8e-43d9-b018-a532fa8ca8d0: 'The Link Address Line 2' # The Link Address Line 2
    2fdeff74-5a22-4299-a0bf-f3b787616e12: 'Food Trucks Events' # Food Trucks Events
    3a61f034-88be-4bc1-a94f-214c405374b1: 'Past Exhibits Page Values' # Past Exhibits Page Values
    3a25069d-8aa9-47ef-89a1-edb4d04fd404: 'Waterloo Innovation Park Leasing Phone Link' # Waterloo Innovation Park Leasing Phone Link
    3c4df632-584d-4ea2-b284-2eadb86e9a40: 'Get In Touch (Footer Links)' # Get In Touch (Footer Links)
    3ccea268-3f4e-423c-9d53-fa8a781f9b58: item # item
    3e1d40f9-bcc2-45e5-a18f-9a845b7988db: 'Button Text' # Button Text
    4b4b1468-382a-43a9-a954-3816f65567a2: Heading # Heading
    4b5a5788-43ee-4012-ba1a-ed2b73b8bbfb: ItemSVG # ItemSVG
    4bf1c6a2-b8b6-48fb-bdac-d9e5804d9ab6: 'Button Text' # Button Text
    4df73862-66da-4140-8eac-6eeb31f2aa4c: 'Button Link' # Button Link
    04e5c194-9ae4-47b7-984b-0892ca576ec9: Images # Images
    5b4ec8f1-aa69-4807-871b-8e4f533f4440: 'Lease now' # Lease now
    5bb2582c-1b3b-4a0a-b234-64558f60c9a9: Image # Image
    5c5be844-5334-4801-a2b8-28db8751a258: 'Call-to-action - Card 1' # Call-to-action - Card 1
    5e5cfcfd-2853-4707-b73e-471efcd57cc8: Default # Default
    5e672526-c38e-4fdc-b248-363c3c83ef20: Subject # Subject
    5f8cb9f8-3c0c-4264-8031-dbfe5b65434a: 'Property Manager Email' # Property Manager Email
    5f70dd77-6168-4476-ba73-4ddee8861a31: 'The Link Address Line 3' # The Link Address Line 3
    6a083dd0-c3a0-40c7-a437-2c5c4610fa50: Heading # Heading
    6aa515b4-55f0-4be2-811d-a261d6ff4532: 'Main Content' # Main Content
    6c5990ae-a749-4e23-b10b-0c65891d8383: 'Waterloo Innovation Park Emergency Phone Link' # Waterloo Innovation Park Emergency Phone Link
    6d96ccd6-4f9c-4b84-b531-cdf34d487529: 'Waterloo Innovation Park Contact Message' # Waterloo Innovation Park Contact Message
    6dc1ef68-7606-4254-8f3e-ab00a4a0b146: 'Button Link' # Button Link
    6f01e9c8-9af2-4589-8d81-a9ed56130cc9: 'Job Title' # Job Title
    6f3a3a27-541a-4c9a-a2ed-48831a335e49: 'The Link Phone Link' # The Link Phone Link
    6f949aa8-1797-4b29-b437-d531558d65c7: 'Button Text' # Button Text
    6f40448c-1230-427f-9e39-355a9fab9fad: 'The Link Contact Message' # The Link Contact Message
    6fea7256-a827-45a0-bc83-3e4ccc95682d: LinkedIn # LinkedIn
    7b3301be-ed48-400a-a679-7b61d6a9fab8: Path # Path
    07bbfe07-a50a-4e7a-a45d-28b6b1ad1f73: 'Button Link' # Button Link
    7bc74160-416f-46f7-9447-6f6fad7b93ec: 'Page Heading' # Page Heading
    7c0905c7-cf97-4e6a-85aa-2dec1a0f13e5: 'Button Text' # Button Text
    7c65acbe-cf3a-4d9d-8c29-198033c701a3: Instagram # Instagram
    7d4ea53b-345f-4ffd-aeb1-c3be93482fcb: 'Lease now' # Lease now
    8a9c949f-a4f8-46c9-b908-e0fba1e95286: Summary # Summary
    8ab1fc90-55da-4dd5-87ff-80cf0364b381: 'The Link Contact Message' # The Link Contact Message
    8adcdb41-46b1-4b0d-9ffd-58c644b0e161: Headline # Headline
    8af21ea5-8ed7-451b-9561-65de6890a24a: Events # Events
    8c6ac355-ba45-47f9-9d6c-13d9f0ecdc30: Limit # Limit
    8c1501f8-32b3-4150-91bc-23f988eb98e5: About # About
    8cef2e04-1901-44a9-bf0c-0f320e8760ba: 'Property Manager Phone Display' # Property Manager Phone Display
    9c87d94e-3edf-4ac7-8d8b-be65d21b54e5: 'Site Navigation' # Site Navigation
    09cde05d-5606-478a-8ab0-d9a6a607d414: Contact # Contact
    9cfc771b-b401-4434-bbd3-e0e94c877314: Uploads # Uploads
    9d0ece9f-df15-4593-94b1-66eb90467427: 'Event Slider Poster Image' # Event Slider Poster Image
    9d42013b-11c6-42cf-b45b-fa037c8bcaba: Title # Title
    9f7eb4c7-c99f-4370-9524-4cf17afa2bbf: 'Button Text' # Button Text
    13ddc265-7d77-4ac9-b0d0-e35357fb61cb: 'Item Title' # Item Title
    15b5c3b8-1bf0-499c-84f7-3a6c39f656d1: 'Phone Link' # Phone Link
    16a6044c-5238-4f14-8aad-ce2d5bf16347: 'Page Summary' # Page Summary
    21bdf77a-7ef8-4373-91e0-b6f8b61e6459: Events # Events
    24a64e3b-2ad3-479e-89dc-1c16e57368ac: Booking # Booking
    25c1ea66-8095-4f2a-971e-611b21bba3aa: Item # Item
    26baa828-2510-4546-ab8a-4866ca224fa2: 'Featured Exhibit' # Featured Exhibit
    26fbc999-074f-40e6-b624-8b8fdeb3f442: 'Waterloo Innovation Park Address Line 3' # Waterloo Innovation Park Address Line 3
    28e33f30-0531-4723-b2ac-1abf27a1bde7: 'Directions Link' # Directions Link
    31a9da1e-374b-4022-b98e-180349d41568: 'Social Links (Footer Links)' # Social Links (Footer Links)
    31aa51d3-2c41-4a98-8464-95f377cc4f07: 'Lease Managers Heading' # Lease Managers Heading
    34e247a1-8be7-4932-a481-cfa735abdba3: 'Exhibition Summary' # Exhibition Summary
    36e3ae0f-08a5-4193-af58-4ed32c350d94: Image # Image
    42a3ddcd-d834-49a3-a79e-21c3f11a6ab6: 'Image panel' # Image panel
    45e9336f-66f8-48d6-8204-ef56340e3519: 'Image Link URL - Card 1' # Image Link URL - Card 1
    45e37949-8c8b-424e-8d3e-8d4b606ed084: Item # Item
    47b5e67e-c01b-4de1-94dd-e0501368e229: Artist # Artist
    51f09ffd-ffd8-4abf-9a71-5bbb77aac42b: 'Event Slider' # Event Slider
    52d8ea63-1195-47df-9693-9e83d7049cd2: 'Lease Managers' # Lease Managers
    56c3c12e-76ff-4b2e-8e3c-382ad3315b5b: 'Section Content Location' # Section Content Location
    075e886a-d174-424c-938b-98d8a9b420ae: 'Image Slider' # Image Slider
    78ee6ec1-b0de-4912-a9f9-ced7e4c1646e: 'Call To Action Panel' # Call To Action Panel
    79a345ab-2e14-443b-b9f2-e4caeb12f9a2: 'Booking Form Recipient Email' # Booking Form Recipient Email
    79e72fa5-51bb-408b-b0b7-ebd8acbbe7b2: 'Panel Title' # Panel Title
    86bf8d52-4937-4435-86ec-d080ca4fd0d7: 'Book Private Event' # Book Private Event
    87f60dce-cac6-4d30-90ef-a6a2040f4d0d: 'Post Limit' # Post Limit
    88c281ce-36ef-4427-abcf-672942cfa723: 'Waterloo Innovation Park Address Line 3' # Waterloo Innovation Park Address Line 3
    95ecac41-0668-4b7c-a8ac-8ec14d07b5af: Subject # Subject
    096ee1d5-cd62-4bd3-9e8f-e8e353b7b6fb: 'Map Embed - Card 1' # Map Embed - Card 1
    96f722d9-925b-4e49-9b34-1494ea93ec47: CTA # CTA
    98ee634c-24f2-4b7c-8d85-b03e13d7c9b4: 'Image Link URL - Card 2' # Image Link URL - Card 2
    99a2cb7d-0c57-4555-83e3-e8cdc93c541b: 'Section Heading' # Section Heading
    114dbb25-d74a-43df-9136-bbc8e4bdeaec: Content # Content
    120c9344-1c5c-4d8c-89d8-34c7e76a8b31: 'Button Link' # Button Link
    169eb7a3-ac32-4f0f-afd8-eb8b92803b1b: 'Event Image' # Event Image
    220d125c-af88-4a55-9b6c-ddae8a634855: 'Content Panel' # Content Panel
    284d17e3-f78c-42b0-a5d0-6cba8be9f1d0: 'Button Text' # Button Text
    317e3c62-d5d8-4d92-8c0f-f2b98ab1bb3f: 'Waterloo Innovation Park Address Line 3' # Waterloo Innovation Park Address Line 3
    335c9bcd-5565-445e-a5cf-ed5a78aac5e7: 'Phone Display' # Phone Display
    354ce86f-294c-4c2e-a75a-be2deb8cb9d0: 'Page Heading' # Page Heading
    402b359e-759c-4938-b279-b9a22b2c6d6a: 'Waterloo Innovation Park' # Waterloo Innovation Park
    453f82b1-cdae-4a97-aeb4-b566b6be9bb6: 'The Link Address Line 1' # The Link Address Line 1
    0493ce96-a299-4502-9f34-15fe3bebbdaa: Artist # Artist
    667c38fa-fdd2-4239-908a-d5f2551515a4: 'Button Link' # Button Link
    687cd2f1-06f5-4174-ab03-40daaa93ad90: 'Panel Title' # Panel Title
    703da12e-6c3e-477c-847b-e1a6b6953e8e: 'Property Name' # Property Name
    705fc584-6fc1-4033-8c33-d552f9684177: 'Call To Action Cards' # Call To Action Cards
    710f40a4-9595-439f-ba53-b0995864d7ca: Heading # Heading
    745cf2fc-6457-41df-a21e-131f47a52823: Content # Content
    750a3bea-3a7c-48b8-a453-41661ad274fa: 'Page Intro' # Page Intro
    771b1ebb-9bc3-4a71-9969-b7e5f1020bb7: 'Property Item' # Property Item
    775aefd3-8b22-4769-bea7-4c07cef58476: 'Page Summary' # Page Summary
    809ce6db-5c77-4e75-9eb9-1d42abe1485b: 'Event Slider Details' # Event Slider Details
    903cf4e1-deba-4181-804b-66520fe03fdc: Image # Image
    1019bad3-fa23-4cdb-bb2b-711a0f1e7bdd: 'The Link Hours of Operation' # The Link Hours of Operation
    1057c048-812f-4e87-b8f7-208e91e4c8fc: 'Button Text' # Button Text
    3906dce9-9071-435f-96fc-05a701d81f46: 'Exhibition Photos' # Exhibition Photos
    4197b684-37e8-427d-9ed0-80a7712911bc: '2 Text Columns With 3 Images' # 2 Text Columns With 3 Images
    4376fc28-a7c8-4264-ae89-8fd01d231075: 'Current Featured Exhibit' # Current Featured Exhibit
    7185e0e8-2762-4d5d-b963-5a2f92ca4f6e: 'Image - Card 2' # Image - Card 2
    08243d9a-7eec-43e3-96fb-51d741633226: 'Image Link Behavior - Card 1' # Image Link Behavior - Card 1
    8267e525-8100-4ca9-9949-0677504ad351: email # email
    9011aff5-8faf-4b49-82cf-6e34d4cdeb2a: Items # Items
    9953bc18-4725-4380-adb8-e62a02c6f0d2: 'Waterloo Innovation Park Emergency Phone Display' # Waterloo Innovation Park Emergency Phone Display
    37175b69-3644-4f1e-a348-e82fd2565057: 'Property Manager Image Caption' # Property Manager Image Caption
    91458f3d-5347-4b47-a507-b691e9a17943: 'Navigation Items' # Navigation Items
    92500a08-4b00-4235-be91-e4a8d210dd0d: 'The Link' # The Link
    300367d4-d29d-4580-a797-6140fdfba101: 'Image - Card 1' # Image - Card 1
    321611e0-0312-43af-a816-cd4e1af60c8f: 'Page Summary' # Page Summary
    433605c5-e0d4-4a9c-a940-6614863fff4a: Heading # Heading
    465854cd-ce73-4e46-905e-7b925a0307e2: 'Exhibition Name' # Exhibition Name
    506955ce-fa3f-407f-9b5c-f7d79b9b1e42: Exhibits # Exhibits
    653749a4-9f6b-4279-9dde-217307ef1f20: 'Image Link Behavior - Card 2' # Image Link Behavior - Card 2
    865120ee-347d-4344-95ec-61b32b775de0: Image # Image
    3653102e-75a7-411d-bfbf-ea9d4de077f4: 'Rollup Image' # Rollup Image
    5835035f-8ddd-4123-9120-309865e31c20: Events # Events
    36824767-1aa1-48a4-b266-8271b9035f52: Default # Default
    38134199-860e-4c8f-9bc6-d1e314e1884a: Leasing # Leasing
    87976032-e2ff-41bd-a53c-f0e4719793b4: Lease # Lease
    89833881-16ce-4ec4-abfd-1f352dc99fd8: Common # Common
    a03da100-4469-4fa1-925f-20e983f46792: 'Waterloo Innovation Park Inquiries Phone Link 2' # Waterloo Innovation Park Inquiries Phone Link 2
    a2e73538-875e-457d-89e7-33b9ac275d91: 'Contact Details' # Contact Details
    a4bee935-0cad-484e-8012-3896bc1f8544: 'Exhibit Rollup' # Exhibit Rollup
    a4f9aa02-65e9-4d0c-8726-9a5782e118c8: 'Waterloo Innovation Park Inquiries Email Link' # Waterloo Innovation Park Inquiries Email Link
    a8b4a8b9-f098-48a3-b3c9-9149a1f3d3e7: 'Art Name' # Art Name
    a8c7d91c-a2c3-4be3-b59e-c74e6e786255: 'Featured Exhibit Rollup' # Featured Exhibit Rollup
    a8d83305-ed06-4c80-971d-0a649f1c0cff: 'Heading - Card 1' # Heading - Card 1
    a51d302d-a33f-4abc-8ffe-bbaf14e67455: Summary # Summary
    a551636e-985a-439e-b78e-c173d8fcc171: 'The Link Phone Link' # The Link Phone Link
    a702171c-dc55-496a-8140-10a53900a54a: 'Button Link' # Button Link
    ac896e2d-c524-475b-9740-71f975b24844: 'The Link Phone Display' # The Link Phone Display
    ad3311a0-c30e-4a01-9405-46dc2bb50f43: 'Page Heading' # Page Heading
    afb98157-06dd-4f20-a32d-7759850afba2: 'Stat Holidays' # Stat Holidays
    b03ae735-63e6-44c4-9ab7-08c44d6089e4: 'Annual Events' # Annual Events
    b1c63a82-dac1-486f-a4f0-a01d8bd252d6: 'Image Vertical Position' # Image Vertical Position
    b3b86eba-c5cd-4b35-99db-9cfe005af4a3: 'Waterloo Innovation Park Emergency Phone Link' # Waterloo Innovation Park Emergency Phone Link
    b3e466e4-7126-4d1b-ae44-65f099f3487e: Year # Year
    b4a72afd-9824-4711-8c7c-654a73ab4125: 'Waterloo Innovation Park Inquiries Phone Display 2' # Waterloo Innovation Park Inquiries Phone Display 2
    b5d074e4-1433-4ae3-85be-1e9d75889129: Calendar # Calendar
    b7cc4e3f-4830-4d21-8c33-0fd45bf0efdf: Facebook # Facebook
    b29d046d-03e7-4eb8-9248-7c870d157e78: 'Property Manager Phone Link' # Property Manager Phone Link
    b41afa41-893f-4b11-970e-c75f2431f0be: 'Learn More Link' # Learn More Link
    b87bb998-aa92-42fc-aee9-1adb2c624a30: 'The Link Address' # The Link Address
    b19956e7-f23d-451e-93c0-712acc2c2b9a: 'Event Description' # Event Description
    b480097d-88f7-49e8-a74a-530aaf07fb0a: 'Annual Events' # Annual Events
    baa2eb32-a191-474e-b7da-50764f46b1e5: Info # Info
    bc928e65-aad4-49d8-bfd2-4bc0a487d1ec: Details # Details
    c21e6094-c48b-4da7-b900-dd593e0d4125: Contact # Contact
    c27feab1-3cbb-4d0e-9bf7-ddcf2ac7a63e: 'Footer Nav Items' # Footer Nav Items
    cb1ecf4b-0473-4929-80c1-830b574c0c48: Price # Price
    cb6d8f3b-a601-41e8-8045-6ab67f0d37b8: 'Waterloo Innovation Park Address' # Waterloo Innovation Park Address
    cb191950-443f-46b3-8914-5a71580972f5: 'Full Name' # Full Name
    cc67c156-422d-4f9e-be71-f3d094eb08e5: 'Art Gallery' # Art Gallery
    cc822dad-031d-4617-957a-65ba55d4ddb3: Instagram # Instagram
    ce352345-5dc4-4b53-a997-af7ff50bf606: Image # Image
    d0d7fc9a-ecb7-4bbf-be37-f1c6061c4856: 'The Link Stats' # The Link Stats
    d088b088-f039-408a-91f6-f1c22c96e161: 'Waterloo Innovation Park (Footer Links)' # Waterloo Innovation Park (Footer Links)
    d3d92310-a896-45d2-810b-4f797da224ff: Summary # Summary
    d4f3f3d0-aeef-48c3-ad9c-af361d012f75: 'The Link (Footer Links)' # The Link (Footer Links)
    d8a9784a-a8a3-4e31-9bf5-73aa7bd6f67c: Home # Home
    d23cf1d8-0be6-484f-8af4-890dfd300055: Instagram # Instagram
    d40fc290-3cb8-4974-b1e9-4ab5e279ce4a: Limit # Limit
    d71f2b99-711c-44b6-ade1-1f5ed6237842: 'Featured Exhibit' # Featured Exhibit
    d686ee64-b930-4740-bac7-6021e74636c5: 'Art Events' # Art Events
    d970ca81-be2c-4ab3-a6d4-156dafe345fe: 'Waterloo Innovation Park Inquiries Phone Link' # Waterloo Innovation Park Inquiries Phone Link
    d4461882-7624-4f6f-ac6c-c06ea4a4689d: 'The Link Email Link' # The Link Email Link
    dd3a546e-11a2-4fd7-a835-04974a2d24ff: 'Booking Contact Info' # Booking Contact Info
    dd6f9a8d-814f-456d-8fc3-d60933f1ed0a: 'Heading - Card 2' # Heading - Card 2
    de802f05-8a3d-4fbd-99ee-3188ab50874c: Content # Content
    e7c7e219-044d-4f4e-813d-a85552002327: 'Waterloo Innovation Park Contact Message' # Waterloo Innovation Park Contact Message
    e12bca54-c3b9-4ba0-9641-31e98bd18527: 'Remove padding top?' # Remove padding top?
    e38e9b53-b834-41a9-aa4c-ec123249d1b7: 'Button Text' # Button Text
    e56aaa87-b266-49f6-888d-6cb43cda2344: Item # Item
    e58e1829-76c2-476c-bf92-2f56e2f3900e: 'Button Link' # Button Link
    e63c55f2-78e4-45cc-9bd8-445b5d5b071a: 'Waterloo Innovation Park Inquiries Phone Display' # Waterloo Innovation Park Inquiries Phone Display
    e696ca9b-87fe-4bc8-8350-a9a82cb85f30: 'The Link Stats Home' # The Link Stats Home
    e760a300-2ccc-4626-9448-8cd0009bfa9c: Images # Images
    e2190436-67a6-4e37-bc3b-b0e52e23f9e7: 'Gallery Items' # Gallery Items
    e3793567-0e66-4d19-ba2b-740920371872: Heading # Heading
    e7435167-064b-48ec-953f-a5da23d3edda: Limit # Limit
    ec1c3db1-02e8-4fdd-b5ad-f3f9bd90e586: 'Button Link' # Button Link
    ec147d51-bd50-4e6e-8f06-fdd1c19ad61a: 'The Link' # The Link
    ee51cfa4-ec13-4103-bf30-68e7c1b63ac5: About # About
    ef382811-26e2-4369-910e-ffa10df24c8b: Account # Account
    f0e3ba41-38ec-4d36-a57e-c1e10c10a52a: 'Past Exhibits Rollup' # Past Exhibits Rollup
    f8eb961a-512c-4bc3-acc8-573a8dbd4de2: Map # Map
    f243fa33-cb56-47f1-a1c2-a1a477cc6307: 'Item Details' # Item Details
    f76199d1-0bdf-4450-81d3-d2aefa255f91: 'Call-to-action - Card 2' # Call-to-action - Card 2
    faa07140-e5cb-4752-9790-0260ba2b62da: 'Waterloo Innovation Park Leasing Phone Display' # Waterloo Innovation Park Leasing Phone Display
    fbbb7b50-c55e-456d-9508-45a83c3219cb: Events # Events
    fbccfcff-4fb4-431b-99a0-3bf93c927097: 'Waterloo Innovation Park Leasing Phone Link' # Waterloo Innovation Park Leasing Phone Link
    fd107921-d306-448f-ad1a-e7c2ef60913c: Home # Home
    fe4b113d-bf1c-4f36-806f-80cb15f3cac8: Title # Title
plugins:
  calendar:
    edition: lite
    enabled: true
    licenseKey: F4E23DFAOGINENN30SCZBG84
    schemaVersion: 4.0.2
    settings:
      allDay: false
      authoredEventEditOnly: ''
      defaultView: month
      demoBannerDisabled: true
      descriptionFieldHandle: null
      eventDuration: 60
      firstDayOfWeek: '0'
      guestAccess: null
      locationFieldHandle: null
      overlapThreshold: 5
      pluginName: null
      quickCreateEnabled: ''
      showDisabledEvents: ''
      showMiniCal: '1'
      timeFormat: auto
      timeInterval: 30
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  instagramfeed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      dump: false
      instagramUser: null
      proxyKey: GPdOk5ibUUjHwnOn8fnY
      subpath: ''
      timeout: 10
      useProxy: true
      useVolume: true
      volume: instagram
  mailjet-adapter:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
system:
  edition: solo
  live: true
  name: 'Waterloo Innovation Park'
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: America/Toronto
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
