fieldLayouts:
  5b7138d7-950b-45b1-8f4a-fa7864d5909f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c27feab1-3cbb-4d0e-9bf7-ddcf2ac7a63e # Footer Nav Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79f74fdd-9cc5-4290-a14f-d84cce22a982
            userCondition: null
            warning: null
            width: 100
        name: 'Link Item'
        uid: d14e5af7-9513-49ed-a44f-16c91bcb259d
        userCondition: null
handle: footerLinksColumn1
name: 'The Link (Footer Links)'
sortOrder: 3
