fieldLayouts:
  dcf77aed-a8dc-4761-9f38-ad404789cf8f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b7cc4e3f-4830-4d21-8c33-0fd45bf0efdf # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6470ea5d-46d6-468a-9656-46bbfaa21a02
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d23cf1d8-0be6-484f-8af4-890dfd300055 # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d1836fb-a64d-4ac4-8534-ae7939acb6d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f2f856e-d16b-4407-9c3b-d0b013f21282 # Twitter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41aaf764-7cde-4563-beb9-96496825f263
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6fea7256-a827-45a0-bc83-3e4ccc95682d # LinkedIn
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8e95dde-c441-4fb9-aa68-291c6cd528fb
            userCondition: null
            warning: null
            width: 100
        name: 'Social Links'
        uid: 5bb7bca8-937b-4295-aeba-5aea7c0c1eb1
        userCondition: null
handle: socialLinks
name: 'Social Links (Footer Links)'
sortOrder: 6
