defaultPlacement: end
enableVersioning: false
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  ada35ad0-4d42-4ca8-bed9-59ff6816f33f:
    enabledByDefault: true
    hasUrls: true
    template: _pages/interior_contact.twig
    uriFormat: contact
type: single
