defaultPlacement: beginning
enableVersioning: true
handle: exhibitions
name: Exhibitions
propagationMethod: all
siteSettings:
  402b359e-759c-4938-b279-b9a22b2c6d6a: # Waterloo Innovation Park
    enabledByDefault: true
    hasUrls: true
    template: _pages/interior_gallery_past.twig
    uriFormat: 'past-exhibitions/{slug}'
structure:
  maxLevels: null
  uid: e7268dfd-80b1-4952-a57b-d01fb2ce0266
type: structure
