defaultPlacement: end
enableVersioning: false
handle: properties
name: Properties
propagationMethod: all
siteSettings:
  402b359e-759c-4938-b279-b9a22b2c6d6a: # Waterloo Innovation Park
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: bd3ddc10-b03a-423a-ad7e-ce00efc12474
type: structure
